FROM nginx:alpine

COPY default.conf /etc/nginx/conf.d/default.conf
COPY fullchain.pem /etc/nginx/conf.d/fullchain.pem
COPY privkey.pem /etc/nginx/conf.d/privkey.pem
COPY options-ssl-nginx.conf /etc/nginx/conf.d/options-ssl-nginx.conf
COPY ssl-dhparams.pem /etc/nginx/conf.d/ssl-dhparams.pem

EXPOSE 443
