FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y python3-pip && \
    pip3 install --upgrade pip && \
    pip3 install -r requirements.txt

RUN ./create_log_file.sh

CMD ["python3", "server.py"]
