FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN ./setup_enode_env_one_time_only.sh
RUN ./venv/bin/pip install -r requirements.txt
RUN ./create_log_file.sh

CMD ["sh", "-c", "python db.py && python server.py"]
